import FotoEjemplo from '../assets/img/room.png';

export const CARDS_DATA = [
  {
    id: 1,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul ',
    price: '230',
  },
  {
    id: 2,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr.  Gonzales',
    price: '230',
  },
  {
    id: 3,
    image: FotoEjemplo,
    type: 'Departamento',
    location: ' Raul Gonzales',
    price: '230',
  },
  {
    id: 4,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul Gonzales',
    price: '23',
  },
  {
    id: 5,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul Gonzales',
    price: '20',
  },
  {
    id: 6,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul Gonzales',
    price: '30',
  },
  {
    id: 7,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul Gonzales',
    price: '30',
  },
  {
    id: 8,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul Gonzales',
    price: '20',
  },
  {
    id: 9,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul Gonzales',
    price: '30',
  },
  {
    id: 10,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul Gonzales',
    price: '30',
  },
  ,
  {
    id: 11,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul Gonzales',
    price: '30',
  },
  {
    id: 12,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul Gonzales',
    price: '20',
  },
  {
    id: 13,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul Gonzales',
    price: '30',
  },
  {
    id: 14,
    image: FotoEjemplo,
    type: 'Departamento',
    location: 'Pnr. Raul Gonzales',
    price: '30',
  },
];